export default class actionTypes {
    static SET_START_DATE_FILTER = "SET_START_DATE_FILTER";
    static SET_END_DATE_FILTER = "SET_END_DATE_FILTER";
    static SET_START_TIME_FILTER = "SET_START_TIME_FILTER";
    static SET_END_TIME_FILTER = "SET_END_TIME_FILTER";
    static SET_EMAIL_FILTER = "SET_EMAIL_FILTER";
    static SET_COMPONENT_FILTER = "SET_COMPONENT_FILTER";   
    static SET_ENVIRONMENT_FILTER = "SET_ENVIRONMENT_FILTER";
    static SET_MESSAGE_FILTER = "SET_MESSAGE_FILTER";
    static SET_ID_FILTER = "SET_ID_FILTER";
    static FETCH_EVENTS_BEGIN = "FETCH_EVENTS_BEGIN";
    static FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";
    static FETCH_EVENTS_FAILURE = "FETCH_EVENTS_FAILURE";
}